variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-python-only:
  image: ubuntu:20.04
  stage: build
  script:
    - $CI_PROJECT_DIR/generate-Dockerfile.sh --python-only
  artifacts:
    paths:
      - .build

deploy-python-only:
  rules:
    - if: '$CI_COMMIT_BRANCH'
      when: always
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/.build --dockerfile $CI_PROJECT_DIR/.build/Dockerfile --destination $CI_REGISTRY/library/gpu-jupyter:$CI_COMMIT_BRANCH-python-only
